### PR TITLE
Update and rename INFO to README.md

### PR DESCRIPTION
**Pull request by fgr0**
`README.md`'s will be fully rendered by Github, even in subfolders.

[Preview](https://github.com/Drakulix/zwreec/tree/laerador-patch-1/utils)

### CODE REVIEW

**Comment by pothos** [comment]
+1

**Comment by felinira** [comment]
Did you just edit the file that says DO NOT EDIT? Like… seriously? (you want to edit https://github.com/Drakulix/zwreec/blob/master/utils/pre.zop too)

**Comment by pothos** [comment]
:D

**Comment by fgr0** [comment]
Funfact: In pre.zop steht auch DO NOT EDIT.

**Comment by pothos** [comment]
Irgendwo muss es ja herkommen ;) Vielleicht noch: … if you read this in file ee.rs

**Comment by berikobama** [comment]
+1

**Pull request merged**
