### PR TITLE
Release/v1.0

### PR DESCRIPTION
**Pull request by felinira**
Release version 1.0. Merge when you think it is appropriate. Please test this version extensively before clicking merge. The button is green but that doesn't mean you should rush to push it. :)

### CODE REVIEW

**Comment by pothos** [comment]
+1

**Comment by felinira** [comment]
Ah ja, wäre einfach dafür, dass hier **alle** ihr okay geben, wenn sie so weit sind. Ich mach das dann mal. +1

**Comment by msaehn** [comment]
+1

**Comment by Drakulix** [comment]
+1

**Comment by stilleben** [comment]
+1

**Comment by benj-zen** [comment]
+1

**Comment by berikobama** [comment]
+1

**Comment by fgr0** [comment]
`-(e^{i*\pi})`

**Pull request merged**
